"use client";
import "../../globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/redux/provider";
import { SessionProvider } from "next-auth/react";
import { Header } from "@/components/main-header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Project Cost Monitoring App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
    <SessionProvider>
      <Providers>{children}</Providers>
    </SessionProvider>
       </body>
     </html>
  );
}
